secrets:
        secret_name : "twillio_creds"
        region_name : "us-west-1"
college:
        name: "WhatsAMatterU"
chatbot:
        name: "Halfway to Heaven Retirement Home"
twillio:
        phone_number: "+18585046379"


